function B_lin = B_lin(L,m,m_0)
%B_lin
%    B_lin = B_lin(L,M,M_0)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    10-Dec-2023 11:01:41

t2 = 1.0./L;
t4 = m.*8.0;
t5 = m.*1.6e+1;
t6 = 1.0./m;
t7 = m_0.*2.8e+1;
t3 = t2.^2;
t8 = t4+t7;
t9 = 1.0./t8;
B_lin = reshape([0.0,t9.*2.8e+1,0.0,t2.*t9.*-3.6e+1,0.0,t2.*t9.*1.2e+1,0.0,t2.*t9.*-4.8e+1,0.0,t3.*t6.*t9.*(m_0.*2.0e+1+t5).*6.0,0.0,t3.*t6.*t9.*(m_0.*4.4e+1+t5).*-6.0],[6,2]);
