function B = B_non_lin(L,m,m_0,theta_1,theta_2)
%B_non_lin
%    B = B_non_lin(L,M,M_0,THETA_1,THETA_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    10-Dec-2023 11:01:41

t2 = cos(theta_1);
t3 = cos(theta_2);
t4 = theta_1+theta_2;
t5 = theta_1.*2.0;
t6 = theta_2.*2.0;
t9 = 1.0./L;
t12 = m.*4.1e+1;
t13 = 1.0./m;
t14 = m_0.*4.6e+1;
t15 = -theta_2;
t7 = cos(t5);
t8 = cos(t6);
t10 = t9.^2;
t11 = cos(t4);
t16 = -t6;
t17 = t3.*4.2e+1;
t18 = t2.*5.4e+1;
t20 = t15+theta_1;
t26 = t5+t15;
t19 = -t18;
t21 = t16+theta_1;
t22 = m.*t8.*3.0;
t23 = cos(t20);
t25 = m.*t7.*2.7e+1;
t27 = t5+t16;
t28 = m.*t11.*9.0;
t30 = cos(t26);
t24 = cos(t21);
t29 = -t25;
t31 = cos(t27);
t32 = -t28;
t34 = m.*t23.*1.5e+1;
t35 = m_0.*t23.*1.2e+1;
t36 = t30.*5.4e+1;
t33 = t24.*1.8e+1;
t37 = m.*t31.*9.0;
t38 = m_0.*t31.*1.8e+1;
t39 = -t37;
t40 = -t38;
t41 = t12+t14+t22+t29+t39+t40;
t42 = 1.0./t41;
B = reshape([0.0,-t42.*(t31.*1.8e+1-4.6e+1),0.0,-t9.*t42.*(t18-t33),0.0,-t9.*t42.*(t17-t36),0.0,t9.*t42.*(t17+t19+t33-t36),0.0,t10.*t13.*t42.*(m.*1.3e+1+m_0.*8.0-t22+t32+t34+t35).*6.0,0.0,t10.*t13.*t42.*(m.*3.7e+1+m_0.*3.2e+1+t29+t32+t34+t35).*-6.0],[6,2]);
